server:
  port:
    8081
  servlet:
    session:
      timeout: 120s
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/SSP
    username: postgres
    password: 1
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none